// <auto-generated />
namespace LMSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lms_systemv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lms_systemv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001072329090_lms_system-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
